CREATE TABLE PROFESOR (
    PROF_ID INTEGER PRIMARY KEY,
    DOCUMENTO TEXT,
    TIPO_DOCUMENTO TEXT,
    NOMBRES TEXT,
    APELLIDOS TEXT,
    USUARIO TEXT,
    CONTRASENA TEXT,
    CORREO_INSTITUCIONAL TEXT,
    TIPO_DOCENTE TEXT,
    ULTIMO_TITULO TEXT
);

CREATE TABLE COORDINADOR (
    COOR_ID INTEGER PRIMARY KEY,
    DOCUMENTO TEXT,
    TIPO_DOCUMENTO TEXT,
    NOMBRES TEXT,
    APELLIDOS TEXT,
    USUARIO TEXT,
    CONTRASENA TEXT,
    CORREO_INSTITUCIONAL TEXT
);

CREATE TABLE EVALUADOR_EXTERNO (
    EVALUADOR_ID INTEGER PRIMARY KEY,
    DOCUMENTO TEXT,
    TIPO_DOCUMENTO TEXT,
    NOMBRES TEXT,
    APELLIDOS TEXT,
    USUARIO TEXT,
    CONTRASENA TEXT,
    CORREO_INSTITUCIONAL TEXT
);

CREATE TABLE ESTUDIANTE (
    ESTUDIANTE_ID INTEGER PRIMARY KEY,
    DOCUMENTO TEXT,
    TIPO_DOCUMENTO TEXT,
    NOMBRES TEXT,
    APELLIDOS TEXT,
    USUARIO TEXT,
    CONTRASENA TEXT,
    CORREO_INSTITUCIONAL TEXT
);

CREATE TABLE PROGRAMA (
    PROGRAMA_ID INTEGER PRIMARY KEY,
    COOR_ID INTEGER,
    NOMBRE TEXT,
    DESCRIPCION TEXT,
    FOREIGN KEY (COOR_ID) REFERENCES COORDINADOR (COOR_ID)
);

CREATE TABLE ASIGNATURA_PLANTILLA (
    AP_ID INTEGER PRIMARY KEY,
    PROGRAMA_ID INTEGER,
    ID TEXT,
    NOMBRE TEXT,
    DESCRIPCION TEXT,
    CREDITOS INTEGER,
    SEMESTRE INTEGER,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA (PROGRAMA_ID)
);

CREATE TABLE COMPETENCIA_PROGRAMA (
    CP_ID INTEGER PRIMARY KEY,
    DESCRIPCION TEXT,
    NIVEL TEXT
);

CREATE TABLE RAP (
    RAP_ID INTEGER PRIMARY KEY,
    CP_ID INTEGER,
    DESCRIPCION TEXT,
    FOREIGN KEY (CP_ID) REFERENCES COMPETENCIA_PROGRAMA (CP_ID)
);

CREATE TABLE RUP (
    RUP_ID INTEGER PRIMARY KEY,
    RAP_ID INTEGER,
    DESCRIPCION TEXT,
    FOREIGN KEY (RAP_ID) REFERENCES RAP (RAP_ID)
);

CREATE TABLE ASIGNATURA_SEMESTRE (
    AS_ID INTEGER PRIMARY KEY,
    AP_ID INTEGER,
    DESCRIPCION TEXT,
    FOREIGN KEY (AP_ID) REFERENCES ASIGNATURA_PLANTILLA (AP_ID)
);

CREATE TABLE COMPETENCIA_SEMESTRE (
    CS_ID INTEGER PRIMARY KEY,
    DESCRIPCION TEXT,
    NIVEL TEXT
);

CREATE TABLE AS_CS (
    CS_ID INTEGER,
    AS_ID INTEGER,
    PRIMARY KEY (CS_ID, AS_ID),
    FOREIGN KEY (CS_ID) REFERENCES COMPETENCIA_SEMESTRE (CS_ID),
    FOREIGN KEY (AS_ID) REFERENCES ASIGNATURA_SEMESTRE (AS_ID)
);

CREATE TABLE RAA (
    RAA_ID INTEGER PRIMARY KEY,
    CS_ID INTEGER,
    DESCRIPCION TEXT,
    FOREIGN KEY (CS_ID) REFERENCES COMPETENCIA_SEMESTRE (CS_ID)
);

CREATE TABLE RUA (
    RUA_ID INTEGER PRIMARY KEY,
    RAA_ID INTEGER,
    DESCRIPCION TEXT,
    FOREIGN KEY (RAA_ID) REFERENCES RAA (RAA_ID)
);

CREATE TABLE AP_CP (
    CP_ID INTEGER,
    AP_ID INTEGER,
    PRIMARY KEY (CP_ID, AP_ID),
    FOREIGN KEY (CP_ID) REFERENCES COMPETENCIA_PROGRAMA (CP_ID),
    FOREIGN KEY (AP_ID) REFERENCES ASIGNATURA_PLANTILLA (AP_ID)
);

CREATE TABLE MATRICULA (
    MATRICULA_ID INTEGER PRIMARY KEY,
    AS_ID INTEGER,
    ESTUDIANTE_ID INTEGER,
    FOREIGN KEY (AS_ID) REFERENCES ASIGNATURA_SEMESTRE (AS_ID),
    FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE (ESTUDIANTE_ID)
);

CREATE TABLE PERIODO (
    PERIODO_ID INTEGER PRIMARY KEY,
    ANO INTEGER,
    CICLO TEXT
);

CREATE TABLE PERIODO_MATRICULA (
    PMAT_ID INTEGER PRIMARY KEY,
    PERIODO_ID INTEGER,
    PROF_ID INTEGER,
    EVALUADOR_ID INTEGER,
    MATRICULA_ID INTEGER,
    FOREIGN KEY (PERIODO_ID) REFERENCES PERIODO (PERIODO_ID),
    FOREIGN KEY (PROF_ID) REFERENCES PROFESOR (PROF_ID),
    FOREIGN KEY (EVALUADOR_ID) REFERENCES EVALUADOR_EXTERNO (EVALUADOR_ID),
    FOREIGN KEY (MATRICULA_ID) REFERENCES MATRICULA (MATRICULA_ID)
);

CREATE TABLE EVALUACION_PROFESOR (
    EVALUACION_PROF_ID INTEGER PRIMARY KEY,
    PROF_ID INTEGER,
    PMAT_ID INTEGER,
    DESCRIPCION TEXT,
    PONDERACION INTEGER,
    NIVEL_DESEMPENO TEXT,
    NOTA REAL,
    FOREIGN KEY (PROF_ID) REFERENCES PROFESOR (PROF_ID),
    FOREIGN KEY (PMAT_ID) REFERENCES PERIODO_MATRICULA (PMAT_ID)
);

CREATE TABLE EVALUACION_EXTERNO (
    EVALUACION_EXT_ID INTEGER PRIMARY KEY,
    EVALUADOR INTEGER,
    PMAT_ID INTEGER,
    DESCRIPCION TEXT,
    PONDERACION INTEGER,
    NIVEL_DESEMPENO TEXT,
    NOTA REAL,
    FOREIGN KEY (EVALUADOR) REFERENCES EVALUADOR_EXTERNO (EVALUADOR_ID),
    FOREIGN KEY (PMAT_ID) REFERENCES PERIODO_MATRICULA (PMAT_ID)
);
