CREATE TABLE PROFESOR (
    PROF_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENTO VARCHAR(255) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    USUARIO VARCHAR(255) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    CORREO_INSTITUCIONAL VARCHAR(255) NOT NULL,
    TIPO_DOCENTE VARCHAR(255) NOT NULL,
    ULTIMO_TITULO VARCHAR(255) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL
);

CREATE TABLE EVALUADOR_EXTERNO (
    EVALUADOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENTO VARCHAR(255) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    USUARIO VARCHAR(255) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    CORREO_INSTITUCIONAL VARCHAR(255) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL
);

CREATE TABLE ESTUDIANTE (
    ESTUDIANTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENTO VARCHAR(255) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    USUARIO VARCHAR(255) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    CORREO_INSTITUCIONAL VARCHAR(255) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL
);

CREATE TABLE COORDINADOR (
    COORDINADOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENTO VARCHAR(255) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    USUARIO VARCHAR(255) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    CORREO_INSTITUCIONAL VARCHAR(255) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL
);

CREATE TABLE PROGRAMA (
    PROGRAMA_ID INT AUTO_INCREMENT PRIMARY KEY,
    COORDINADOR_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DURACION_SEMESTRES INT NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    MODALIDAD VARCHAR(255) NOT NULL,
    FACULTAD VARCHAR(255) NOT NULL,
    TIPO_PROGRAMA VARCHAR(255) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL,
    FOREIGN KEY (COORDINADOR_ID) REFERENCES COORDINADOR (COORDINADOR_ID)
);

CREATE TABLE ASIGNATURA_PLANTILLA (
    AP_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROGRAMA_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    CREDITOS INT NOT NULL,
    SEMESTRE INT NOT NULL,
    HORAS_SEMANA INT NOT NULL,
    MODALIDAD VARCHAR(255) NOT NULL,
    TIPO_MATERIA VARCHAR(255) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA (PROGRAMA_ID)
);

CREATE TABLE COMPETENCIA_PROGRAMA (
    CP_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROGRAMA_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    NIVEL VARCHAR(255) NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    ESTADO ENUM('0', '1') NOT NULL,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA (PROGRAMA_ID)
);

CREATE TABLE AP_CP (
    CP_ID INT NOT NULL,
    AP_ID INT NOT NULL,
    PRIMARY KEY (CP_ID, AP_ID),
    FOREIGN KEY (CP_ID) REFERENCES COMPETENCIA_PROGRAMA (CP_ID),
    FOREIGN KEY (AP_ID) REFERENCES ASIGNATURA_PLANTILLA (AP_ID)
);

CREATE TABLE RAP (
    RAP_ID INT AUTO_INCREMENT PRIMARY KEY,
    CP_ID INT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (CP_ID) REFERENCES COMPETENCIA_PROGRAMA (CP_ID)
);

CREATE TABLE RUP (
    RUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    RAP_ID INT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (RAP_ID) REFERENCES RAP (RAP_ID)
);

CREATE TABLE ASIGNATURA_SEMESTRE (
    AS_ID INT AUTO_INCREMENT PRIMARY KEY,
    AP_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    GRUPO VARCHAR(255) NOT NULL,
    CREDITOS INT NOT NULL,
    SEMESTRE INT NOT NULL,
    MODALIDAD VARCHAR(255) NOT NULL,
    TIPO_MATERIA VARCHAR(255) NOT NULL,
    FOREIGN KEY (AP_ID) REFERENCES ASIGNATURA_PLANTILLA (AP_ID)
);

CREATE TABLE COMPETENCIA_SEMESTRE (
    CS_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    NIVEL VARCHAR(255) NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL
);

CREATE TABLE AS_CS (
    AS_ID INT NOT NULL,
    CS_ID INT NOT NULL,
    PRIMARY KEY (AS_ID, CS_ID),
    FOREIGN KEY (AS_ID) REFERENCES ASIGNATURA_SEMESTRE (AS_ID),
    FOREIGN KEY (CS_ID) REFERENCES COMPETENCIA_SEMESTRE (CS_ID)
);

CREATE TABLE RAA (
    RAA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CS_ID INT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (CS_ID) REFERENCES COMPETENCIA_SEMESTRE (CS_ID)
);

CREATE TABLE RUA (
    RUA_ID INT AUTO_INCREMENT PRIMARY KEY,
    RAA_ID INT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (RAA_ID) REFERENCES RAA (RAA_ID)
);

CREATE TABLE PERIODO (
    PERIODO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ANO INT NOT NULL,
    CICLO VARCHAR(255) NOT NULL
);

CREATE TABLE PERIODO_MATRICULA (
    PMAT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_ID INT NOT NULL,
    PROF_ID INT NOT NULL,
    EVALUADOR_ID INT NOT NULL,
    FOREIGN KEY (PERIODO_ID) REFERENCES PERIODO (PERIODO_ID),
    FOREIGN KEY (PROF_ID) REFERENCES PROFESOR (PROF_ID),
    FOREIGN KEY (EVALUADOR_ID) REFERENCES EVALUADOR_EXTERNO (EVALUADOR_ID)
);

CREATE TABLE MATRICULA (
    MATRICULA_ID INT AUTO_INCREMENT PRIMARY KEY,
    PMAT_ID INT NOT NULL,
    AS_ID INT NOT NULL,
    ESTUDIANTE_ID INT NOT NULL,
    FOREIGN KEY (AS_ID) REFERENCES ASIGNATURA_SEMESTRE (AS_ID),
    FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE (ESTUDIANTE_ID),
    FOREIGN KEY (PMAT_ID) REFERENCES PERIODO_MATRICULA (PMAT_ID)
);

CREATE TABLE EVALUACION_PROFESOR (
    PROFEV_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROF_ID INT NOT NULL,
    RUA_ID INT NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    NIVEL_DESEMPENO VARCHAR(255) NOT NULL,
    NOTA DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (PROF_ID) REFERENCES PROFESOR (PROF_ID),
    FOREIGN KEY (RUA_ID) REFERENCES RUA (RUA_ID)
);

CREATE TABLE EVALUACION_EXTERNO (
    EXTEV_ID INT AUTO_INCREMENT PRIMARY KEY,
    EVALUADOR_ID INT NOT NULL,
    RUA_ID INT NOT NULL,
    PONDERACION DECIMAL(5,2) NOT NULL,
    NIVEL_DESEMPENO VARCHAR(255) NOT NULL,
    NOTA DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (EVALUADOR_ID) REFERENCES EVALUADOR_EXTERNO (EVALUADOR_ID),
    FOREIGN KEY (RUA_ID) REFERENCES RUA (RUA_ID)
);