CREATE TABLE PROFESOR (
    PROF_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENTO TEXT NOT NULL,
    TIPO_DOCUMENTO TEXT NOT NULL,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    USUARIO TEXT NOT NULL,
    CONTRASENA TEXT NOT NULL,
    CORREO_INSTITUCIONAL TEXT NOT NULL,
    TIPO_DOCENTE TEXT NOT NULL,
    ULTIMO_TITULO TEXT NOT NULL,
    ESTADO TEXT NOT NULL
);

CREATE TABLE EVALUADOR_EXTERNO (
    EVALUADOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENTO TEXT NOT NULL,
    TIPO_DOCUMENTO TEXT NOT NULL,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    USUARIO TEXT NOT NULL,
    CONTRASENA TEXT NOT NULL,
    CORREO_INSTITUCIONAL TEXT NOT NULL,
    ESTADO TEXT NOT NULL
);

CREATE TABLE ESTUDIANTE (
    ESTUDIANTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENTO TEXT NOT NULL,
    TIPO_DOCUMENTO TEXT NOT NULL,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    USUARIO TEXT NOT NULL,
    CONTRASENA TEXT NOT NULL,
    CORREO_INSTITUCIONAL TEXT NOT NULL,
    ESTADO TEXT NOT NULL
);

CREATE TABLE COORDINADOR (
    COORDINADOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENTO TEXT NOT NULL,
    TIPO_DOCUMENTO TEXT NOT NULL,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    USUARIO TEXT NOT NULL,
    CONTRASENA TEXT NOT NULL,
    CORREO_INSTITUCIONAL TEXT NOT NULL,
    ESTADO TEXT NOT NULL
);

CREATE TABLE PROGRAMA (
    PROGRAMA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COORDINADOR_ID INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    DURACION_SEMESTRES INTEGER NOT NULL,
    TITULO TEXT NOT NULL,
    MODALIDAD TEXT NOT NULL,
    FACULTAD TEXT NOT NULL,
    TIPO_PROGRAMA TEXT NOT NULL,
    ESTADO TEXT NOT NULL,
    FOREIGN KEY (COORDINADOR_ID) REFERENCES COORDINADOR (COORDINADOR_ID)
);

CREATE TABLE ASIGNATURA_PLANTILLA (
    AP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROGRAMA_ID INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    CREDITOS INTEGER NOT NULL,
    SEMESTRE INTEGER NOT NULL,
    HORAS_SEMANA INTEGER NOT NULL,
    MODALIDAD TEXT NOT NULL,
    TIPO_MATERIA TEXT NOT NULL,
    ESTADO TEXT NOT NULL,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA (PROGRAMA_ID)
);

CREATE TABLE COMPETENCIA_PROGRAMA (
    CP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROGRAMA_ID INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    NIVEL TEXT NOT NULL,
    PONDERACION REAL NOT NULL,
    ESTADO TEXT NOT NULL,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA (PROGRAMA_ID)
);

CREATE TABLE AP_CP (
    CP_ID INTEGER NOT NULL,
    AP_ID INTEGER NOT NULL,
    PRIMARY KEY (CP_ID, AP_ID),
    FOREIGN KEY (CP_ID) REFERENCES COMPETENCIA_PROGRAMA (CP_ID),
    FOREIGN KEY (AP_ID) REFERENCES ASIGNATURA_PLANTILLA (AP_ID)
);

CREATE TABLE RAP (
    RAP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CP_ID INTEGER NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION REAL NOT NULL,
    FOREIGN KEY (CP_ID) REFERENCES COMPETENCIA_PROGRAMA (CP_ID)
);

CREATE TABLE RUP (
    RUP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RAP_ID INTEGER NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION REAL NOT NULL,
    FOREIGN KEY (RAP_ID) REFERENCES RAP (RAP_ID)
);

CREATE TABLE ASIGNATURA_SEMESTRE (
    AS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AP_ID INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    GRUPO TEXT NOT NULL,
    CREDITOS INTEGER NOT NULL,
    SEMESTRE INTEGER NOT NULL,
    MODALIDAD TEXT NOT NULL,
    TIPO_MATERIA TEXT NOT NULL,
    FOREIGN KEY (AP_ID) REFERENCES ASIGNATURA_PLANTILLA (AP_ID)
);

CREATE TABLE COMPETENCIA_SEMESTRE (
    CS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    NIVEL TEXT NOT NULL,
    PONDERACION REAL NOT NULL
);

CREATE TABLE AS_CS (
    AS_ID INTEGER NOT NULL,
    CS_ID INTEGER NOT NULL,
    PRIMARY KEY (AS_ID, CS_ID),
    FOREIGN KEY (AS_ID) REFERENCES ASIGNATURA_SEMESTRE (AS_ID),
    FOREIGN KEY (CS_ID) REFERENCES COMPETENCIA_SEMESTRE (CS_ID)
);

CREATE TABLE RAA (
    RAA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CS_ID INTEGER NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION REAL NOT NULL,
    FOREIGN KEY (CS_ID) REFERENCES COMPETENCIA_SEMESTRE (CS_ID)
);

CREATE TABLE RUA (
    RUA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RAA_ID INTEGER NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PONDERACION REAL NOT NULL,
    FOREIGN KEY (RAA_ID) REFERENCES RAA (RAA_ID)
);

CREATE TABLE PERIODO (
    PERIODO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ANO INTEGER NOT NULL,
    CICLO TEXT NOT NULL
);

CREATE TABLE MATRICULA (
    MATRICULA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AS_ID INTEGER NOT NULL,
    ESTUDIANTE_ID INTEGER NOT NULL,
    FOREIGN KEY (AS_ID) REFERENCES ASIGNATURA_SEMESTRE (AS_ID),
    FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE (ESTUDIANTE_ID)
);

CREATE TABLE PERIODO_MATRICULA (
    PMAT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PERIODO INTEGER NOT NULL,
    PROF_ID INTEGER NOT NULL,
    EVALUADOR_ID INTEGER NOT NULL,
    MATRICULA_ID INTEGER NOT NULL,
    FOREIGN KEY (PERIODO) REFERENCES PERIODO (PERIODO_ID),
    FOREIGN KEY (PROF_ID) REFERENCES PROFESOR (PROF_ID),
    FOREIGN KEY (EVALUADOR_ID) REFERENCES EVALUADOR_EXTERNO (EVALUADOR_ID),
    FOREIGN KEY (MATRICULA_ID) REFERENCES MATRICULA (MATRICULA_ID)
);

CREATE TABLE EVALUACION_PROFESOR (
    PROFEV_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROF_ID INTEGER NOT NULL,
    PMAT_ID INTEGER NOT NULL,
    RUA_ID INTEGER NOT NULL,
    PONDERACION REAL NOT NULL,
    NIVEL_DESEMPENO TEXT NOT NULL,
    NOTA REAL NOT NULL,
    FOREIGN KEY (PROF_ID) REFERENCES PROFESOR (PROF_ID),
    FOREIGN KEY (PMAT_ID) REFERENCES PERIODO_MATRICULA (PMAT_ID),
    FOREIGN KEY (RUA_ID) REFERENCES RUA (RUA_ID)
);

CREATE TABLE EVALUACION_EXTERNO (
    EXTEV_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVALUADOR_ID INTEGER NOT NULL,
    PMAT_ID INTEGER NOT NULL,
    RUA_ID INTEGER NOT NULL,
    PONDERACION REAL NOT NULL,
    NIVEL_DESEMPENO TEXT NOT NULL,
    NOTA REAL NOT NULL,
    FOREIGN KEY (EVALUADOR_ID) REFERENCES EVALUADOR_EXTERNO (EVALUADOR_ID),
    FOREIGN KEY (PMAT_ID) REFERENCES PERIODO_MATRICULA (PMAT_ID),
    FOREIGN KEY (RUA_ID) REFERENCES RUA (RUA_ID)
);
